DROP TABLE IF EXISTS bougt_books;
DROP TABLE IF EXISTS comments_table;
DROP VIEW IF EXISTS book_view;
DROP VIEW IF EXISTS book_files;
DROP TABLE IF EXISTS book_table;
DROP TABLE IF EXISTS genre_table;
DROP TABLE IF EXISTS user_table;
DROP TABLE IF EXISTS admin_table;
DROP TABLE IF EXISTS access_table;
